version: "3.9"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "5432:5432"